name: Test, Build and Deploy to HostGator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      continue-on-error: false
      
    - name: Test build process
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Verify build output
      run: |
        echo "Checking if build was successful..."
        if [ ! -f "dist/index.html" ]; then
          echo "❌ Build failed - index.html not found"
          exit 1
        fi
        echo "✅ Build verification passed"
        ls -la dist/
        

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test  # This job only runs if 'test' job succeeds
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on main branch pushes
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application for production
      run: npm run build
      env:
        NODE_ENV: production
      
    - name: Verify production build
      run: |
        echo "Production build completed. Contents of dist folder:"
        ls -la dist/
        echo "Checking critical files..."
        [ -f "dist/index.html" ] && echo "✅ index.html exists" || (echo "❌ index.html missing" && exit 1)
        [ -f "dist/.htaccess" ] && echo "✅ .htaccess exists" || echo "⚠️  .htaccess missing"
        
    - name: Deploy to HostGator Frontend Folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /frontend/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          **/README.md
        dry-run: false
        
    - name: Deployment Success Notification
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "🌐 Your app should be available at: https://yourdomain.com"
        echo "📁 Files are stored in: /frontend/ directory"
        echo "⏰ Deployed at: $(date)" 